spring:
  datasource:
    url: jdbc:mysql://localhost:3306/archivage?serverTimezone=UTC&useSSL=false
    username: root
    password: adminbeel
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: '@project.name@'
  profiles:
    active: '@spring.profiles.active@'
  jta:
    enabled: false
  jpa:
    mapping-resources:
     - META-INF/account.orm.xml
     - META-INF/classificationNature.orm.xml
     - META-INF/client.orm.xml
     - META-INF/contract.orm.xml
     - META-INF/document.orm.xml
     - META-INF/event.orm.xml
     - META-INF/history-statistic.orm.xml
     - META-INF/user.orm.xml
     - META-INF/destructionList.orm.xml
    open-in-view: false
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, configprops, logfile, metrics, env, loggers, httptrace, mappings, threaddump
application:
  version: '@project.version@'
  timezone: ${user.timezone}
server:
  ssl:
    enabled: true
    key-alias: archivage-projet
    key-store-type: PKCS12
    key-store: classpath:archivage-projet.p12
    key-store-password: archivageWeb
  port: 8443

